/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * Sonda liveness — não toca o banco, não expõe detalhe interno (RS-052).
 * @summary Saúde sem banco
 */
export const LerSaudeResponse = zod.object({
  "status": zod.enum(['ok'])
}).describe('Resposta da sonda liveness.')


/**
 * Sonda readiness — toca o banco, não expõe detalhe interno (RS-052).
 * @summary Prontidão com banco
 */
export const LerProntidaoResponse = zod.object({
  "status": zod.enum(['ok']),
  "banco": zod.enum(['ok'])
}).describe('Resposta da sonda readiness.')


/**
 * Abre sessão pré-login (RF-001). Pública com rate limit (RS-012/RS-050). Mutação: exige confirmação de origem CSRF (RS-040, implementação em F-04). Falha devolve mensagem genérica (RS-001/RS-002).
 * @summary Login com email e senha
 */
export const criarSessaoBodyEmailMax = 254;

export const criarSessaoBodySenhaMax = 256;



export const CriarSessaoBody = zod.object({
  "email": zod.email().max(criarSessaoBodyEmailMax),
  "senha": zod.string().min(1).max(criarSessaoBodySenhaMax)
}).describe('Credenciais de login (RF-001).')

export const CriarSessaoResponse = zod.object({
  "pedeTotp": zod.boolean().describe('Verdadeiro quando o login exige concluir o TOTP (RF-002).'),
  "usuarioId": zod.uuid().optional().describe('Identificador do usuário dono da sessão.')
}).describe('Sessão aberta (F-04 implementa; aqui só o formato).')


/**
 * Encerra a sessão (RF-008). Mutação: exige confirmação de origem CSRF (RS-040, implementação em F-04).
 * @summary Logout
 */
export const EncerrarSessaoResponse = zod.void()


/**
 * Valida o código TOTP sobre a sessão pré-login e efetiva a sessão (RF-001/RF-002). Mutação: exige confirmação de origem CSRF (RS-040, implementação em F-04).
 * @summary Validar TOTP e efetivar sessão
 */
export const confirmarTotpBodyCodigoRegExp = new RegExp('^[0-9]{6}$');


export const ConfirmarTotpBody = zod.object({
  "codigo": zod.string().regex(confirmarTotpBodyCodigoRegExp)
}).describe('Código TOTP de 6 dígitos (RF-001).')

export const ConfirmarTotpResponse = zod.object({
  "pedeTotp": zod.boolean().describe('Verdadeiro quando o login exige concluir o TOTP (RF-002).'),
  "usuarioId": zod.uuid().optional().describe('Identificador do usuário dono da sessão.')
}).describe('Sessão aberta (F-04 implementa; aqui só o formato).')
