// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ContaTotpEntradaAcao.
const (
	Confirmar ContaTotpEntradaAcao = "confirmar"
	Desativar ContaTotpEntradaAcao = "desativar"
	Iniciar   ContaTotpEntradaAcao = "iniciar"
)

// Valid indicates whether the value is a known member of the ContaTotpEntradaAcao enum.
func (e ContaTotpEntradaAcao) Valid() bool {
	switch e {
	case Confirmar:
		return true
	case Desativar:
		return true
	case Iniciar:
		return true
	default:
		return false
	}
}

// Defines values for ErroErroCodigo.
const (
	ErroErroCodigoConflitoRegra   ErroErroCodigo = "ConflitoRegra"
	ErroErroCodigoErroInterno     ErroErroCodigo = "ErroInterno"
	ErroErroCodigoLimiteExcedido  ErroErroCodigo = "LimiteExcedido"
	ErroErroCodigoNaoAutenticado  ErroErroCodigo = "NaoAutenticado"
	ErroErroCodigoNaoEncontrado   ErroErroCodigo = "NaoEncontrado"
	ErroErroCodigoPayloadInvalido ErroErroCodigo = "PayloadInvalido"
	ErroErroCodigoSemPermissao    ErroErroCodigo = "SemPermissao"
)

// Valid indicates whether the value is a known member of the ErroErroCodigo enum.
func (e ErroErroCodigo) Valid() bool {
	switch e {
	case ErroErroCodigoConflitoRegra:
		return true
	case ErroErroCodigoErroInterno:
		return true
	case ErroErroCodigoLimiteExcedido:
		return true
	case ErroErroCodigoNaoAutenticado:
		return true
	case ErroErroCodigoNaoEncontrado:
		return true
	case ErroErroCodigoPayloadInvalido:
		return true
	case ErroErroCodigoSemPermissao:
		return true
	default:
		return false
	}
}

// Defines values for ProntidaoBanco.
const (
	ProntidaoBancoOk ProntidaoBanco = "ok"
)

// Valid indicates whether the value is a known member of the ProntidaoBanco enum.
func (e ProntidaoBanco) Valid() bool {
	switch e {
	case ProntidaoBancoOk:
		return true
	default:
		return false
	}
}

// Defines values for ProntidaoStatus.
const (
	ProntidaoStatusOk ProntidaoStatus = "ok"
)

// Valid indicates whether the value is a known member of the ProntidaoStatus enum.
func (e ProntidaoStatus) Valid() bool {
	switch e {
	case ProntidaoStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for SaudeStatus.
const (
	SaudeStatusOk SaudeStatus = "ok"
)

// Valid indicates whether the value is a known member of the SaudeStatus enum.
func (e SaudeStatus) Valid() bool {
	switch e {
	case SaudeStatusOk:
		return true
	default:
		return false
	}
}

// ContaSenhaEntrada Troca da própria senha (RS-006). A nova senha não pode repetir a atual.
type ContaSenhaEntrada struct {
	SenhaAtual string `json:"senhaAtual"`
	SenhaNova  string `json:"senhaNova"`
}

// ContaTotpEntrada Gestão do 2FA próprio (RF-003). `iniciar` dispensa `codigo`; `confirmar` e `desativar` exigem o código de 6 dígitos (validado no backend; códigos nunca persistidos, RS-010).
type ContaTotpEntrada struct {
	Acao   ContaTotpEntradaAcao `json:"acao"`
	Codigo *string              `json:"codigo,omitempty"`
}

// ContaTotpEntradaAcao defines model for ContaTotpEntrada.Acao.
type ContaTotpEntradaAcao string

// ContaTotpResposta Resposta da gestão do 2FA próprio. `iniciar` devolve `segredo` + `otpauthUrl` (cadastrar no autenticador e confirmar em seguida); `confirmar` devolve a sessão efetivada (`pedeTotp: false`).
type ContaTotpResposta struct {
	// OtpauthUrl URL otpauth:// para QR code no autenticador (só em `iniciar`).
	OtpauthUrl *string `json:"otpauthUrl,omitempty"`

	// PedeTotp Verdadeiro enquanto a sessão seguir pré-login (RF-002).
	PedeTotp *bool `json:"pedeTotp,omitempty"`

	// Segredo Segredo TOTP em base32 (só em `iniciar`; cadastrar e guardar no autenticador).
	Segredo *string `json:"segredo,omitempty"`

	// UsuarioId Identificador do usuário dono da sessão.
	UsuarioId *openapi_types.UUID `json:"usuarioId,omitempty"`
}

// Erro Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type Erro struct {
	Erro struct {
		// Codigo Código estável do erro.
		Codigo   ErroErroCodigo `json:"codigo"`
		Detalhes *[]ErroCampo   `json:"detalhes,omitempty"`

		// Mensagem Mensagem em pt-BR, sem detalhe interno (RS-044).
		Mensagem string `json:"mensagem"`
	} `json:"erro"`
}

// ErroErroCodigo Código estável do erro.
type ErroErroCodigo string

// ErroCampo Detalhe por campo (só em 400).
type ErroCampo struct {
	// Campo Caminho do campo no payload.
	Campo    *string `json:"campo,omitempty"`
	Problema *string `json:"problema,omitempty"`
}

// Prontidao Resposta da sonda readiness.
type Prontidao struct {
	Banco  ProntidaoBanco  `json:"banco"`
	Status ProntidaoStatus `json:"status"`
}

// ProntidaoBanco defines model for Prontidao.Banco.
type ProntidaoBanco string

// ProntidaoStatus defines model for Prontidao.Status.
type ProntidaoStatus string

// Saude Resposta da sonda liveness.
type Saude struct {
	Status SaudeStatus `json:"status"`
}

// SaudeStatus defines model for Saude.Status.
type SaudeStatus string

// SenhaRedefinicaoResposta Senha temporária de uso único (RF-005, RS-007). Devolvida uma única vez; exige troca no próximo login.
type SenhaRedefinicaoResposta struct {
	SenhaTemporaria string `json:"senhaTemporaria"`
}

// Sessao Sessão aberta (F-04 implementa; aqui só o formato).
type Sessao struct {
	// PedeTotp Verdadeiro quando o login exige concluir o TOTP (RF-002).
	PedeTotp bool `json:"pedeTotp"`

	// UsuarioId Identificador do usuário dono da sessão.
	UsuarioId *openapi_types.UUID `json:"usuarioId,omitempty"`
}

// SessaoCriarEntrada Credenciais de login (RF-001).
type SessaoCriarEntrada struct {
	Email openapi_types.Email `json:"email"`
	Senha string              `json:"senha"`
}

// TotpConfirmarEntrada Código TOTP de 6 dígitos (RF-001).
type TotpConfirmarEntrada struct {
	Codigo string `json:"codigo"`
}

// ErroInterno Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type ErroInterno = Erro

// LimiteExcedido Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type LimiteExcedido = Erro

// NaoAutenticado Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type NaoAutenticado = Erro

// NaoEncontrado Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type NaoEncontrado = Erro

// PayloadInvalido Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type PayloadInvalido = Erro

// SemPermissao Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
type SemPermissao = Erro

// TrocarSenhaPropriaJSONRequestBody defines body for TrocarSenhaPropria for application/json ContentType.
type TrocarSenhaPropriaJSONRequestBody = ContaSenhaEntrada

// GerirTotpProprioJSONRequestBody defines body for GerirTotpProprio for application/json ContentType.
type GerirTotpProprioJSONRequestBody = ContaTotpEntrada

// CriarSessaoJSONRequestBody defines body for CriarSessao for application/json ContentType.
type CriarSessaoJSONRequestBody = SessaoCriarEntrada

// ConfirmarTotpJSONRequestBody defines body for ConfirmarTotp for application/json ContentType.
type ConfirmarTotpJSONRequestBody = TotpConfirmarEntrada

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// TrocarSenhaPropria Trocar a própria senha
	// (POST /api/conta/senha)
	TrocarSenhaPropria(w http.ResponseWriter, r *http.Request)
	// GerirTotpProprio Iniciar, confirmar ou desativar o 2FA próprio
	// (POST /api/conta/totp)
	GerirTotpProprio(w http.ResponseWriter, r *http.Request)
	// LerSaude Saúde sem banco
	// (GET /api/saude)
	LerSaude(w http.ResponseWriter, r *http.Request)
	// LerProntidao Prontidão com banco
	// (GET /api/saude/pronto)
	LerProntidao(w http.ResponseWriter, r *http.Request)
	// EncerrarSessao Logout
	// (DELETE /api/sessao)
	EncerrarSessao(w http.ResponseWriter, r *http.Request)
	// CriarSessao Login com email e senha
	// (POST /api/sessao)
	CriarSessao(w http.ResponseWriter, r *http.Request)
	// ConfirmarTotp Validar TOTP e efetivar sessão
	// (POST /api/sessao/totp)
	ConfirmarTotp(w http.ResponseWriter, r *http.Request)
	// RedefinirSenhaUsuario Redefinir a senha de um usuário (temporária de uso único)
	// (POST /api/usuarios/{id}/senha-redefinicao)
	RedefinirSenhaUsuario(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ReiniciarTotpUsuario Reiniciar o TOTP de um usuário (autenticador perdido)
	// (POST /api/usuarios/{id}/totp-reinicio)
	ReiniciarTotpUsuario(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// TrocarSenhaPropria Trocar a própria senha
// (POST /api/conta/senha)
func (_ Unimplemented) TrocarSenhaPropria(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GerirTotpProprio Iniciar, confirmar ou desativar o 2FA próprio
// (POST /api/conta/totp)
func (_ Unimplemented) GerirTotpProprio(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LerSaude Saúde sem banco
// (GET /api/saude)
func (_ Unimplemented) LerSaude(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LerProntidao Prontidão com banco
// (GET /api/saude/pronto)
func (_ Unimplemented) LerProntidao(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// EncerrarSessao Logout
// (DELETE /api/sessao)
func (_ Unimplemented) EncerrarSessao(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CriarSessao Login com email e senha
// (POST /api/sessao)
func (_ Unimplemented) CriarSessao(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ConfirmarTotp Validar TOTP e efetivar sessão
// (POST /api/sessao/totp)
func (_ Unimplemented) ConfirmarTotp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RedefinirSenhaUsuario Redefinir a senha de um usuário (temporária de uso único)
// (POST /api/usuarios/{id}/senha-redefinicao)
func (_ Unimplemented) RedefinirSenhaUsuario(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ReiniciarTotpUsuario Reiniciar o TOTP de um usuário (autenticador perdido)
// (POST /api/usuarios/{id}/totp-reinicio)
func (_ Unimplemented) ReiniciarTotpUsuario(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// TrocarSenhaPropria operation middleware
func (siw *ServerInterfaceWrapper) TrocarSenhaPropria(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TrocarSenhaPropria(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GerirTotpProprio operation middleware
func (siw *ServerInterfaceWrapper) GerirTotpProprio(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GerirTotpProprio(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LerSaude operation middleware
func (siw *ServerInterfaceWrapper) LerSaude(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LerSaude(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LerProntidao operation middleware
func (siw *ServerInterfaceWrapper) LerProntidao(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LerProntidao(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EncerrarSessao operation middleware
func (siw *ServerInterfaceWrapper) EncerrarSessao(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EncerrarSessao(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CriarSessao operation middleware
func (siw *ServerInterfaceWrapper) CriarSessao(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CriarSessao(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmarTotp operation middleware
func (siw *ServerInterfaceWrapper) ConfirmarTotp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmarTotp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedefinirSenhaUsuario operation middleware
func (siw *ServerInterfaceWrapper) RedefinirSenhaUsuario(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedefinirSenhaUsuario(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReiniciarTotpUsuario operation middleware
func (siw *ServerInterfaceWrapper) ReiniciarTotpUsuario(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReiniciarTotpUsuario(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/saude", wrapper.LerSaude)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/saude/pronto", wrapper.LerProntidao)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/sessao", wrapper.EncerrarSessao)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessao", wrapper.CriarSessao)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessao/totp", wrapper.ConfirmarTotp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/conta/totp", wrapper.GerirTotpProprio)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/conta/senha", wrapper.TrocarSenhaPropria)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/usuarios/{id}/senha-redefinicao", wrapper.RedefinirSenhaUsuario)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/usuarios/{id}/totp-reinicio", wrapper.ReiniciarTotpUsuario)
	})

	return r
}

type ErroInternoJSONResponse Erro

type LimiteExcedidoJSONResponse Erro

type NaoAutenticadoJSONResponse Erro

type NaoEncontradoJSONResponse Erro

type PayloadInvalidoJSONResponse Erro

type SemPermissaoJSONResponse Erro

type TrocarSenhaPropriaRequestObject struct {
	Body *TrocarSenhaPropriaJSONRequestBody
}

type TrocarSenhaPropriaResponseObject interface {
	VisitTrocarSenhaPropriaResponse(w http.ResponseWriter) error
}

type TrocarSenhaPropria204Response struct {
}

func (response TrocarSenhaPropria204Response) VisitTrocarSenhaPropriaResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type TrocarSenhaPropria400JSONResponse struct{ PayloadInvalidoJSONResponse }

func (response TrocarSenhaPropria400JSONResponse) VisitTrocarSenhaPropriaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TrocarSenhaPropria401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response TrocarSenhaPropria401JSONResponse) VisitTrocarSenhaPropriaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type TrocarSenhaPropria429JSONResponse struct{ LimiteExcedidoJSONResponse }

func (response TrocarSenhaPropria429JSONResponse) VisitTrocarSenhaPropriaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type TrocarSenhaPropria500JSONResponse struct{ ErroInternoJSONResponse }

func (response TrocarSenhaPropria500JSONResponse) VisitTrocarSenhaPropriaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GerirTotpProprioRequestObject struct {
	Body *GerirTotpProprioJSONRequestBody
}

type GerirTotpProprioResponseObject interface {
	VisitGerirTotpProprioResponse(w http.ResponseWriter) error
}

type GerirTotpProprio200JSONResponse ContaTotpResposta

func (response GerirTotpProprio200JSONResponse) VisitGerirTotpProprioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GerirTotpProprio400JSONResponse struct{ PayloadInvalidoJSONResponse }

func (response GerirTotpProprio400JSONResponse) VisitGerirTotpProprioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GerirTotpProprio401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response GerirTotpProprio401JSONResponse) VisitGerirTotpProprioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GerirTotpProprio403JSONResponse struct{ SemPermissaoJSONResponse }

func (response GerirTotpProprio403JSONResponse) VisitGerirTotpProprioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GerirTotpProprio429JSONResponse struct{ LimiteExcedidoJSONResponse }

func (response GerirTotpProprio429JSONResponse) VisitGerirTotpProprioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GerirTotpProprio500JSONResponse struct{ ErroInternoJSONResponse }

func (response GerirTotpProprio500JSONResponse) VisitGerirTotpProprioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LerSaudeRequestObject struct {
}

type LerSaudeResponseObject interface {
	VisitLerSaudeResponse(w http.ResponseWriter) error
}

type LerSaude200JSONResponse Saude

func (response LerSaude200JSONResponse) VisitLerSaudeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LerSaude500JSONResponse Erro

func (response LerSaude500JSONResponse) VisitLerSaudeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LerProntidaoRequestObject struct {
}

type LerProntidaoResponseObject interface {
	VisitLerProntidaoResponse(w http.ResponseWriter) error
}

type LerProntidao200JSONResponse Prontidao

func (response LerProntidao200JSONResponse) VisitLerProntidaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LerProntidao500JSONResponse Erro

func (response LerProntidao500JSONResponse) VisitLerProntidaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type EncerrarSessaoRequestObject struct {
}

type EncerrarSessaoResponseObject interface {
	VisitEncerrarSessaoResponse(w http.ResponseWriter) error
}

type EncerrarSessao204Response struct {
}

func (response EncerrarSessao204Response) VisitEncerrarSessaoResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type EncerrarSessao401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response EncerrarSessao401JSONResponse) VisitEncerrarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EncerrarSessao500JSONResponse struct{ ErroInternoJSONResponse }

func (response EncerrarSessao500JSONResponse) VisitEncerrarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CriarSessaoRequestObject struct {
	Body *CriarSessaoJSONRequestBody
}

type CriarSessaoResponseObject interface {
	VisitCriarSessaoResponse(w http.ResponseWriter) error
}

type CriarSessao200JSONResponse Sessao

func (response CriarSessao200JSONResponse) VisitCriarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CriarSessao400JSONResponse struct{ PayloadInvalidoJSONResponse }

func (response CriarSessao400JSONResponse) VisitCriarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CriarSessao401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response CriarSessao401JSONResponse) VisitCriarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CriarSessao429JSONResponse struct{ LimiteExcedidoJSONResponse }

func (response CriarSessao429JSONResponse) VisitCriarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CriarSessao500JSONResponse struct{ ErroInternoJSONResponse }

func (response CriarSessao500JSONResponse) VisitCriarSessaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmarTotpRequestObject struct {
	Body *ConfirmarTotpJSONRequestBody
}

type ConfirmarTotpResponseObject interface {
	VisitConfirmarTotpResponse(w http.ResponseWriter) error
}

type ConfirmarTotp200JSONResponse Sessao

func (response ConfirmarTotp200JSONResponse) VisitConfirmarTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmarTotp400JSONResponse struct{ PayloadInvalidoJSONResponse }

func (response ConfirmarTotp400JSONResponse) VisitConfirmarTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmarTotp401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response ConfirmarTotp401JSONResponse) VisitConfirmarTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmarTotp429JSONResponse struct{ LimiteExcedidoJSONResponse }

func (response ConfirmarTotp429JSONResponse) VisitConfirmarTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmarTotp500JSONResponse struct{ ErroInternoJSONResponse }

func (response ConfirmarTotp500JSONResponse) VisitConfirmarTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuarioRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type RedefinirSenhaUsuarioResponseObject interface {
	VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error
}

type RedefinirSenhaUsuario200JSONResponse SenhaRedefinicaoResposta

func (response RedefinirSenhaUsuario200JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuario400JSONResponse struct{ PayloadInvalidoJSONResponse }

func (response RedefinirSenhaUsuario400JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuario401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response RedefinirSenhaUsuario401JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuario403JSONResponse struct{ SemPermissaoJSONResponse }

func (response RedefinirSenhaUsuario403JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuario404JSONResponse struct{ NaoEncontradoJSONResponse }

func (response RedefinirSenhaUsuario404JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuario429JSONResponse struct{ LimiteExcedidoJSONResponse }

func (response RedefinirSenhaUsuario429JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RedefinirSenhaUsuario500JSONResponse struct{ ErroInternoJSONResponse }

func (response RedefinirSenhaUsuario500JSONResponse) VisitRedefinirSenhaUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReiniciarTotpUsuarioRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ReiniciarTotpUsuarioResponseObject interface {
	VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error
}

type ReiniciarTotpUsuario204Response struct {
}

func (response ReiniciarTotpUsuario204Response) VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ReiniciarTotpUsuario401JSONResponse struct{ NaoAutenticadoJSONResponse }

func (response ReiniciarTotpUsuario401JSONResponse) VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReiniciarTotpUsuario403JSONResponse struct{ SemPermissaoJSONResponse }

func (response ReiniciarTotpUsuario403JSONResponse) VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ReiniciarTotpUsuario404JSONResponse struct{ NaoEncontradoJSONResponse }

func (response ReiniciarTotpUsuario404JSONResponse) VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReiniciarTotpUsuario429JSONResponse struct{ LimiteExcedidoJSONResponse }

func (response ReiniciarTotpUsuario429JSONResponse) VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ReiniciarTotpUsuario500JSONResponse struct{ ErroInternoJSONResponse }

func (response ReiniciarTotpUsuario500JSONResponse) VisitReiniciarTotpUsuarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// TrocarSenhaPropria Trocar a própria senha
	// (POST /api/conta/senha)
	TrocarSenhaPropria(ctx context.Context, request TrocarSenhaPropriaRequestObject) (TrocarSenhaPropriaResponseObject, error)
	// GerirTotpProprio Iniciar, confirmar ou desativar o 2FA próprio
	// (POST /api/conta/totp)
	GerirTotpProprio(ctx context.Context, request GerirTotpProprioRequestObject) (GerirTotpProprioResponseObject, error)
	// LerSaude Saúde sem banco
	// (GET /api/saude)
	LerSaude(ctx context.Context, request LerSaudeRequestObject) (LerSaudeResponseObject, error)
	// LerProntidao Prontidão com banco
	// (GET /api/saude/pronto)
	LerProntidao(ctx context.Context, request LerProntidaoRequestObject) (LerProntidaoResponseObject, error)
	// EncerrarSessao Logout
	// (DELETE /api/sessao)
	EncerrarSessao(ctx context.Context, request EncerrarSessaoRequestObject) (EncerrarSessaoResponseObject, error)
	// CriarSessao Login com email e senha
	// (POST /api/sessao)
	CriarSessao(ctx context.Context, request CriarSessaoRequestObject) (CriarSessaoResponseObject, error)
	// ConfirmarTotp Validar TOTP e efetivar sessão
	// (POST /api/sessao/totp)
	ConfirmarTotp(ctx context.Context, request ConfirmarTotpRequestObject) (ConfirmarTotpResponseObject, error)
	// RedefinirSenhaUsuario Redefinir a senha de um usuário (temporária de uso único)
	// (POST /api/usuarios/{id}/senha-redefinicao)
	RedefinirSenhaUsuario(ctx context.Context, request RedefinirSenhaUsuarioRequestObject) (RedefinirSenhaUsuarioResponseObject, error)
	// ReiniciarTotpUsuario Reiniciar o TOTP de um usuário (autenticador perdido)
	// (POST /api/usuarios/{id}/totp-reinicio)
	ReiniciarTotpUsuario(ctx context.Context, request ReiniciarTotpUsuarioRequestObject) (ReiniciarTotpUsuarioResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// TrocarSenhaPropria operation middleware
func (sh *strictHandler) TrocarSenhaPropria(w http.ResponseWriter, r *http.Request) {
	var request TrocarSenhaPropriaRequestObject

	var body TrocarSenhaPropriaJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TrocarSenhaPropria(ctx, request.(TrocarSenhaPropriaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TrocarSenhaPropria")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TrocarSenhaPropriaResponseObject); ok {
		if err := validResponse.VisitTrocarSenhaPropriaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GerirTotpProprio operation middleware
func (sh *strictHandler) GerirTotpProprio(w http.ResponseWriter, r *http.Request) {
	var request GerirTotpProprioRequestObject

	var body GerirTotpProprioJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GerirTotpProprio(ctx, request.(GerirTotpProprioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GerirTotpProprio")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GerirTotpProprioResponseObject); ok {
		if err := validResponse.VisitGerirTotpProprioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LerSaude operation middleware
func (sh *strictHandler) LerSaude(w http.ResponseWriter, r *http.Request) {
	var request LerSaudeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LerSaude(ctx, request.(LerSaudeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LerSaude")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LerSaudeResponseObject); ok {
		if err := validResponse.VisitLerSaudeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LerProntidao operation middleware
func (sh *strictHandler) LerProntidao(w http.ResponseWriter, r *http.Request) {
	var request LerProntidaoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LerProntidao(ctx, request.(LerProntidaoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LerProntidao")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LerProntidaoResponseObject); ok {
		if err := validResponse.VisitLerProntidaoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EncerrarSessao operation middleware
func (sh *strictHandler) EncerrarSessao(w http.ResponseWriter, r *http.Request) {
	var request EncerrarSessaoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EncerrarSessao(ctx, request.(EncerrarSessaoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EncerrarSessao")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EncerrarSessaoResponseObject); ok {
		if err := validResponse.VisitEncerrarSessaoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CriarSessao operation middleware
func (sh *strictHandler) CriarSessao(w http.ResponseWriter, r *http.Request) {
	var request CriarSessaoRequestObject

	var body CriarSessaoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CriarSessao(ctx, request.(CriarSessaoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CriarSessao")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CriarSessaoResponseObject); ok {
		if err := validResponse.VisitCriarSessaoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmarTotp operation middleware
func (sh *strictHandler) ConfirmarTotp(w http.ResponseWriter, r *http.Request) {
	var request ConfirmarTotpRequestObject

	var body ConfirmarTotpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmarTotp(ctx, request.(ConfirmarTotpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmarTotp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConfirmarTotpResponseObject); ok {
		if err := validResponse.VisitConfirmarTotpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RedefinirSenhaUsuario operation middleware
func (sh *strictHandler) RedefinirSenhaUsuario(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RedefinirSenhaUsuarioRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RedefinirSenhaUsuario(ctx, request.(RedefinirSenhaUsuarioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RedefinirSenhaUsuario")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RedefinirSenhaUsuarioResponseObject); ok {
		if err := validResponse.VisitRedefinirSenhaUsuarioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReiniciarTotpUsuario operation middleware
func (sh *strictHandler) ReiniciarTotpUsuario(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ReiniciarTotpUsuarioRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReiniciarTotpUsuario(ctx, request.(ReiniciarTotpUsuarioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReiniciarTotpUsuario")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReiniciarTotpUsuarioResponseObject); ok {
		if err := validResponse.VisitReiniciarTotpUsuarioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
