/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Resposta da gestão do 2FA próprio. `iniciar` devolve `segredo` + `otpauthUrl` (cadastrar no autenticador e confirmar em seguida); `confirmar` devolve a sessão efetivada (`pedeTotp: false`).
 */
export interface ContaTotpResposta {
  /**
     * Segredo TOTP em base32 (só em `iniciar`; cadastrar e guardar no autenticador).
     * @maxLength 100
     */
  segredo?: string;
  /**
     * URL otpauth:// para QR code no autenticador (só em `iniciar`).
     * @maxLength 500
     */
  otpauthUrl?: string;
  /** Verdadeiro enquanto a sessão seguir pré-login (RF-002). */
  pedeTotp?: boolean;
  /** Identificador do usuário dono da sessão. */
  usuarioId?: string;
}
