/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */
import type { ContaTotpEntradaAcao } from './contaTotpEntradaAcao';

/**
 * Gestão do 2FA próprio (RF-003). `iniciar` dispensa `codigo`; `confirmar` e `desativar` exigem o código de 6 dígitos (validado no backend; códigos nunca persistidos, RS-010).
 */
export interface ContaTotpEntrada {
  acao: ContaTotpEntradaAcao;
  /** @pattern ^[0-9]{6}$ */
  codigo?: string;
}
