/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Detalhe por campo (só em 400).
 */
export interface ErroCampo {
  /**
     * Caminho do campo no payload.
     * @maxLength 200
     */
  campo?: string;
  /** @maxLength 500 */
  problema?: string;
}
