/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */
import type { ErroErro } from './erroErro';

/**
 * Envelope de erro padrão — todos os erros, sem exceção (SRS §15.3).
 */
export interface Erro {
  erro: ErroErro;
}
