/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */
import type { ErroCampo } from './erroCampo';
import type { ErroErroCodigo } from './erroErroCodigo';

export type ErroErro = {
  /** Código estável do erro. */
  codigo: ErroErroCodigo;
  /**
     * Mensagem em pt-BR, sem detalhe interno (RS-044).
     * @maxLength 500
     */
  mensagem: string;
  detalhes?: ErroCampo[];
};
