/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

export * from './conflitoRegraResponse';
export * from './erro';
export * from './erroCampo';
export * from './erroErro';
export * from './erroErroCodigo';
export * from './erroInternoResponse';
export * from './limiteExcedidoResponse';
export * from './naoAutenticadoResponse';
export * from './naoEncontradoResponse';
export * from './paginaDe';
export * from './paginaDeItensItem';
export * from './paginaMeta';
export * from './payloadInvalidoResponse';
export * from './prontidao';
export * from './prontidaoBanco';
export * from './prontidaoStatus';
export * from './saude';
export * from './saudeStatus';
export * from './semPermissaoResponse';
export * from './sessao';
export * from './sessaoCriarEntrada';
export * from './totpConfirmarEntrada';
