/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadados de paginação (SRS §15.2/§15.4).
 */
export interface PaginaMeta {
  /** @minimum 1 */
  pagina: number;
  /**
     * @minimum 1
     * @maximum 100
     */
  porPagina: number;
  /** @minimum 0 */
  totalItens: number;
}
