/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */
import type { PaginaDeItensItem } from './paginaDeItensItem';
import type { PaginaMeta } from './paginaMeta';

/**
 * Envelope de resposta paginada (convenção SRS §15.2: `PaginaDe<T>`). Listagens futuras especializam `itens`; declarado aqui para firmar a convenção mesmo ainda sem uso (F-02).
 */
export interface PaginaDe {
  meta: PaginaMeta;
  /** Itens da página (schema especializado por listagem). */
  itens: PaginaDeItensItem[];
}
