/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Senha temporária de uso único (RF-005, RS-007). Devolvida uma única vez; exige troca no próximo login.
 */
export interface SenhaRedefinicaoResposta {
  /** @maxLength 100 */
  senhaTemporaria: string;
}
