/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Credenciais de login (RF-001).
 */
export interface SessaoCriarEntrada {
  /** @maxLength 254 */
  email: string;
  /**
     * @minLength 1
     * @maxLength 256
     */
  senha: string;
}
