/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Escola Sacre Coeur des Enfants
 * Contrato da API — fonte da verdade (AGENTS.md §6, SRS §15). Escopo F-02: saúde (`/api/saude`) + sessão (`/api/sessao`) e envelope de erro padrão. Novos recursos entram aqui antes do código, tarefa a tarefa.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Sessão aberta (F-04 implementa; aqui só o formato).
 */
export interface Sessao {
  /** Verdadeiro quando o login exige concluir o TOTP (RF-002). */
  pedeTotp: boolean;
  /** Identificador do usuário dono da sessão. */
  usuarioId?: string;
}
