// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const encerrarSessoesDoUsuario = `-- name: EncerrarSessoesDoUsuario :exec
DELETE FROM sessions
WHERE token IN (
  SELECT token FROM sessao_usuario WHERE usuario_id = $1
)
`

func (q *Queries) EncerrarSessoesDoUsuario(ctx context.Context, usuarioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, encerrarSessoesDoUsuario, usuarioID)
	return err
}

const getHttprate = `-- name: GetHttprate :one
SELECT contagem
FROM httprate_contador
WHERE chave = $1 AND janela = $2
`

type GetHttprateParams struct {
	Chave  string             `json:"chave"`
	Janela pgtype.Timestamptz `json:"janela"`
}

func (q *Queries) GetHttprate(ctx context.Context, arg GetHttprateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getHttprate, arg.Chave, arg.Janela)
	var contagem int64
	err := row.Scan(&contagem)
	return contagem, err
}

const getLoginBloqueio = `-- name: GetLoginBloqueio :one
SELECT email, falhas, bloqueado_ate, atualizado_em
FROM login_bloqueio
WHERE email = $1
`

func (q *Queries) GetLoginBloqueio(ctx context.Context, email string) (LoginBloqueio, error) {
	row := q.db.QueryRow(ctx, getLoginBloqueio, email)
	var i LoginBloqueio
	err := row.Scan(
		&i.Email,
		&i.Falhas,
		&i.BloqueadoAte,
		&i.AtualizadoEm,
	)
	return i, err
}

const incrementarHttprate = `-- name: IncrementarHttprate :one
INSERT INTO httprate_contador (chave, janela, contagem)
VALUES ($1, $2, 1)
ON CONFLICT (chave, janela) DO UPDATE SET
  contagem = httprate_contador.contagem + 1
RETURNING contagem
`

type IncrementarHttprateParams struct {
	Chave  string             `json:"chave"`
	Janela pgtype.Timestamptz `json:"janela"`
}

func (q *Queries) IncrementarHttprate(ctx context.Context, arg IncrementarHttprateParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementarHttprate, arg.Chave, arg.Janela)
	var contagem int64
	err := row.Scan(&contagem)
	return contagem, err
}

const listarCodigosPerfilDoUsuario = `-- name: ListarCodigosPerfilDoUsuario :many

SELECT p.codigo
FROM usuario_perfil up
JOIN perfil p ON p.id = up.perfil_id
WHERE up.usuario_id = $1
`

// queries/auth.sql — sessão, bloqueio e rate limit (F-04). RS-031.
func (q *Queries) ListarCodigosPerfilDoUsuario(ctx context.Context, usuarioID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listarCodigosPerfilDoUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var codigo string
		if err := rows.Scan(&codigo); err != nil {
			return nil, err
		}
		items = append(items, codigo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetLoginBloqueio = `-- name: ResetLoginBloqueio :exec
DELETE FROM login_bloqueio WHERE email = $1
`

func (q *Queries) ResetLoginBloqueio(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, resetLoginBloqueio, email)
	return err
}

const upsertLoginFalha = `-- name: UpsertLoginFalha :one
INSERT INTO login_bloqueio (email, falhas, bloqueado_ate, atualizado_em)
VALUES ($1, 1, $2, now())
ON CONFLICT (email) DO UPDATE SET
  falhas = login_bloqueio.falhas + 1,
  bloqueado_ate = EXCLUDED.bloqueado_ate,
  atualizado_em = now()
RETURNING email, falhas, bloqueado_ate, atualizado_em
`

type UpsertLoginFalhaParams struct {
	Email        string             `json:"email"`
	BloqueadoAte pgtype.Timestamptz `json:"bloqueado_ate"`
}

func (q *Queries) UpsertLoginFalha(ctx context.Context, arg UpsertLoginFalhaParams) (LoginBloqueio, error) {
	row := q.db.QueryRow(ctx, upsertLoginFalha, arg.Email, arg.BloqueadoAte)
	var i LoginBloqueio
	err := row.Scan(
		&i.Email,
		&i.Falhas,
		&i.BloqueadoAte,
		&i.AtualizadoEm,
	)
	return i, err
}

const vincularSessaoUsuario = `-- name: VincularSessaoUsuario :exec
INSERT INTO sessao_usuario (token, usuario_id)
VALUES ($1, $2)
ON CONFLICT (token) DO UPDATE SET usuario_id = EXCLUDED.usuario_id
`

type VincularSessaoUsuarioParams struct {
	Token     string      `json:"token"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) VincularSessaoUsuario(ctx context.Context, arg VincularSessaoUsuarioParams) error {
	_, err := q.db.Exec(ctx, vincularSessaoUsuario, arg.Token, arg.UsuarioID)
	return err
}
