// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conta.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ativarTotp = `-- name: AtivarTotp :exec
UPDATE usuario
SET totp_ativo = true,
    atualizado_em = now()
WHERE id = $1
`

func (q *Queries) AtivarTotp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ativarTotp, id)
	return err
}

const definirTotpSecreto = `-- name: DefinirTotpSecreto :exec
UPDATE usuario
SET totp_secreto_cifrado = $2,
    atualizado_em = now()
WHERE id = $1
`

type DefinirTotpSecretoParams struct {
	ID                 pgtype.UUID `json:"id"`
	TotpSecretoCifrado []byte      `json:"totp_secreto_cifrado"`
}

func (q *Queries) DefinirTotpSecreto(ctx context.Context, arg DefinirTotpSecretoParams) error {
	_, err := q.db.Exec(ctx, definirTotpSecreto, arg.ID, arg.TotpSecretoCifrado)
	return err
}

const getUsuarioPorID = `-- name: GetUsuarioPorID :one

SELECT id, nome, email, hash_senha, senha_temporaria, troca_obrigatoria,
       totp_secreto_cifrado, totp_ativo, ativo, criado_em, atualizado_em,
       sessoes_invalidas_antes_de
FROM usuario
WHERE id = $1
LIMIT 1
`

// queries/conta.sql — conta própria e gestão de usuários (F-05). RS-031.
//
// Requisitos: RF-005, RF-007; RS-006..009 (troca encerra sessões, temporária
// de uso único com troca obrigatória, TOTP com segredo cifrado).
// Só SQL parametrizado via sqlc/pgx; sem concatenação.
func (q *Queries) GetUsuarioPorID(ctx context.Context, id pgtype.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.HashSenha,
		&i.SenhaTemporaria,
		&i.TrocaObrigatoria,
		&i.TotpSecretoCifrado,
		&i.TotpAtivo,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SessoesInvalidasAntesDe,
	)
	return i, err
}

const invalidarSessoesDoUsuario = `-- name: InvalidarSessoesDoUsuario :exec
UPDATE usuario
SET sessoes_invalidas_antes_de = $2,
    atualizado_em = now()
WHERE id = $1
`

type InvalidarSessoesDoUsuarioParams struct {
	ID                      pgtype.UUID        `json:"id"`
	SessoesInvalidasAntesDe pgtype.Timestamptz `json:"sessoes_invalidas_antes_de"`
}

func (q *Queries) InvalidarSessoesDoUsuario(ctx context.Context, arg InvalidarSessoesDoUsuarioParams) error {
	_, err := q.db.Exec(ctx, invalidarSessoesDoUsuario, arg.ID, arg.SessoesInvalidasAntesDe)
	return err
}

const redefinirSenhaAdmin = `-- name: RedefinirSenhaAdmin :exec
UPDATE usuario
SET hash_senha = $2,
    senha_temporaria = true,
    troca_obrigatoria = true,
    atualizado_em = now()
WHERE id = $1
`

type RedefinirSenhaAdminParams struct {
	ID        pgtype.UUID `json:"id"`
	HashSenha string      `json:"hash_senha"`
}

func (q *Queries) RedefinirSenhaAdmin(ctx context.Context, arg RedefinirSenhaAdminParams) error {
	_, err := q.db.Exec(ctx, redefinirSenhaAdmin, arg.ID, arg.HashSenha)
	return err
}

const reiniciarTotp = `-- name: ReiniciarTotp :exec
UPDATE usuario
SET totp_secreto_cifrado = NULL,
    totp_ativo = false,
    atualizado_em = now()
WHERE id = $1
`

func (q *Queries) ReiniciarTotp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reiniciarTotp, id)
	return err
}

const trocarSenhaPropria = `-- name: TrocarSenhaPropria :exec
UPDATE usuario
SET hash_senha = $2,
    senha_temporaria = false,
    troca_obrigatoria = false,
    atualizado_em = now()
WHERE id = $1
`

type TrocarSenhaPropriaParams struct {
	ID        pgtype.UUID `json:"id"`
	HashSenha string      `json:"hash_senha"`
}

func (q *Queries) TrocarSenhaPropria(ctx context.Context, arg TrocarSenhaPropriaParams) error {
	_, err := q.db.Exec(ctx, trocarSenhaPropria, arg.ID, arg.HashSenha)
	return err
}
