// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fundacao.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsuarioPorEmail = `-- name: GetUsuarioPorEmail :one

SELECT id, nome, email, hash_senha, senha_temporaria, troca_obrigatoria,
       totp_secreto_cifrado, totp_ativo, ativo, criado_em, atualizado_em
FROM usuario
WHERE email = $1
LIMIT 1
`

// queries/fundacao.sql — queries mínimas da fundação (F-03).
//
// Requisitos: RS-031 (só SQL parametrizado via sqlc/pgx; sem concatenação).
// Escopo desta tarefa: buscar usuário por e-mail (base do login em F-04) e
// inserir registro de auditoria (RS-010). Novas queries entram aqui tarefa a
// tarefa e o código é regenerado com `task gerar:sql` (AGENTS.md §6).
func (q *Queries) GetUsuarioPorEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioPorEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.HashSenha,
		&i.SenhaTemporaria,
		&i.TrocaObrigatoria,
		&i.TotpSecretoCifrado,
		&i.TotpAtivo,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const insertAuditoria = `-- name: InsertAuditoria :one
INSERT INTO auditoria (usuario_id, acao, recurso, detalhe, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, usuario_id, acao, recurso, detalhe, ip, criado_em
`

type InsertAuditoriaParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Acao      string      `json:"acao"`
	Recurso   string      `json:"recurso"`
	Detalhe   []byte      `json:"detalhe"`
	Ip        pgtype.Text `json:"ip"`
}

func (q *Queries) InsertAuditoria(ctx context.Context, arg InsertAuditoriaParams) (Auditorium, error) {
	row := q.db.QueryRow(ctx, insertAuditoria,
		arg.UsuarioID,
		arg.Acao,
		arg.Recurso,
		arg.Detalhe,
		arg.Ip,
	)
	var i Auditorium
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Acao,
		&i.Recurso,
		&i.Detalhe,
		&i.Ip,
		&i.CriadoEm,
	)
	return i, err
}
