// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auditorium struct {
	ID        int64              `json:"id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Acao      string             `json:"acao"`
	Recurso   string             `json:"recurso"`
	Detalhe   []byte             `json:"detalhe"`
	Ip        pgtype.Text        `json:"ip"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Notificacao struct {
	ID        pgtype.UUID        `json:"id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Titulo    string             `json:"titulo"`
	Mensagem  string             `json:"mensagem"`
	LidaEm    pgtype.Timestamptz `json:"lida_em"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Perfil struct {
	ID     pgtype.UUID `json:"id"`
	Codigo string      `json:"codigo"`
	Nome   string      `json:"nome"`
}

type Usuario struct {
	ID                 pgtype.UUID        `json:"id"`
	Nome               string             `json:"nome"`
	Email              string             `json:"email"`
	HashSenha          string             `json:"hash_senha"`
	SenhaTemporaria    bool               `json:"senha_temporaria"`
	TrocaObrigatoria   bool               `json:"troca_obrigatoria"`
	TotpSecretoCifrado []byte             `json:"totp_secreto_cifrado"`
	TotpAtivo          bool               `json:"totp_ativo"`
	Ativo              bool               `json:"ativo"`
	CriadoEm           pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm       pgtype.Timestamptz `json:"atualizado_em"`
}

type UsuarioPerfil struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	PerfilID  pgtype.UUID `json:"perfil_id"`
}
