// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auditorium struct {
	ID        int64              `json:"id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Acao      string             `json:"acao"`
	Recurso   string             `json:"recurso"`
	Detalhe   []byte             `json:"detalhe"`
	Ip        pgtype.Text        `json:"ip"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type HttprateContador struct {
	Chave    string             `json:"chave"`
	Janela   pgtype.Timestamptz `json:"janela"`
	Contagem int64              `json:"contagem"`
}

type LoginBloqueio struct {
	Email        string             `json:"email"`
	Falhas       int32              `json:"falhas"`
	BloqueadoAte pgtype.Timestamptz `json:"bloqueado_ate"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type Notificacao struct {
	ID        pgtype.UUID        `json:"id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Titulo    string             `json:"titulo"`
	Mensagem  string             `json:"mensagem"`
	LidaEm    pgtype.Timestamptz `json:"lida_em"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Perfil struct {
	ID     pgtype.UUID `json:"id"`
	Codigo string      `json:"codigo"`
	Nome   string      `json:"nome"`
}

type SessaoUsuario struct {
	Token     string             `json:"token"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Usuario struct {
	ID                      pgtype.UUID        `json:"id"`
	Nome                    string             `json:"nome"`
	Email                   string             `json:"email"`
	HashSenha               string             `json:"hash_senha"`
	SenhaTemporaria         bool               `json:"senha_temporaria"`
	TrocaObrigatoria        bool               `json:"troca_obrigatoria"`
	TotpSecretoCifrado      []byte             `json:"totp_secreto_cifrado"`
	TotpAtivo               bool               `json:"totp_ativo"`
	Ativo                   bool               `json:"ativo"`
	CriadoEm                pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm            pgtype.Timestamptz `json:"atualizado_em"`
	SessoesInvalidasAntesDe pgtype.Timestamptz `json:"sessoes_invalidas_antes_de"`
}

type UsuarioPerfil struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	PerfilID  pgtype.UUID `json:"perfil_id"`
}
